### ISSUE TITLE
Warn users that `.env` is sourced

### ISSUE THREAD

**Issue by vidurb** [ryoppippi/fish-poetry#4]
You should warn users that this plugin automatically reads `.env` files into the running shell. Since it's not in scope of the main use case (running `poetry shell` automatically) it may be unexpected behaviour for users (I know it was for me), and it can cause a variety of problems. I'm happy to open a PR updating the README if you accept contributions.

**Comment by ryoppippi** [comment]
@vidurb 
Sorry for my late response and thank you for your great feature request.
Yes, if you can please send a PR to this

**Comment by ryoppippi** [comment]
If you are okay, please create PR which has features like:

- this plugin does not load `.env` file in defualt
- when the user set some environmental variable (like `FISH_PIPENV_ENV_LOAD`, you can name it whatever), the `.env` file will be loaded.

I'm okay that I make this feature, but I think it is better that you create this one!
Again, thank you for reporting this issue!!!

**Comment by vidurb** [comment]
Happy to. I'll make the necessary changes and tag you in a PR. 👍🏼
